### ISSUE TITLE
User can only select projects on VS Code startup

### ISSUE THREAD

**Issue by mhrastegari** [JaneySprings/DotRush#2]
This popup for selecting projects shows up only on startup and I don't see any options anywhere to show it again!

![image](https://github.com/JaneySprings/DotRush/assets/42671084/37cc927a-36cd-432f-bc11-3fe39098ad89)

From my .NET Meteor experience, it can/better be a button on status bar.

**Comment by JaneySprings** [comment]
Hi, @mhrastegari! If you open a folder that contains **more than one** project files, you will see this window. It may be useful, for example, when you open `maui` repository. 

I recommend using `.code-workspace`. From readme:
> Empowering you with [Code Workspaces](https://code.visualstudio.com/docs/editor/workspaces) DotRush lets you effortlessly combine multiple projects and apply different settings to them. DotRush seamlessly activates all features when you add a new folder to your workspace. **Note that .sln files are not supported**.

For example: https://github.com/JaneySprings/DotNet.Meteor/blob/main/all.code-workspace
The `folders` section is enough for you.

**Comment by mhrastegari** [comment]
Thanks for the guiding @JaneySprings!
I just tested that! that's awesome and works great! 🤩 

But still, it would be really useful for those who are not using the workspace feature to choose which projects to load without restarting VS Code!

**Comment by JaneySprings** [comment]
Yes, I think it is a good idea.
