### ISSUE TITLE
Failed to register .NET SDK

### ISSUE THREAD

**Issue by tritao** [JaneySprings/DotRush#5]
Just opening the extension on a new project created by `dotnet new console`.

```
~/dev/csharp-app$ dotnet --list-sdks
8.0.401 [/home/joao/.dotnet/sdk]
~/dev/csharp-app$ dotnet --list-runtimes
Microsoft.AspNetCore.App 8.0.8 [/home/joao/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 8.0.8 [/home/joao/.dotnet/shared/Microsoft.NETCore.App]
~/dev/csharp-app$ echo $DOTNET_ROOT
/home/joao/.dotnet
```

![image](https://github.com/user-attachments/assets/77cb0d39-51e4-4a56-b7b6-0c982546b2f4)

Any ideas?

**Comment by JaneySprings** [comment]
Hi @tritao ! This error doesn’t stop the extension. Can you continue to use the extension while ignoring this error? or is intellisense not working?

**Comment by JaneySprings** [comment]
I think that you have installed dotnet via `dotnet-install.sh` script (dotnet inside `.dotnet` folder). 
I have installed dotnet with `apt-get install dotnet-sdk-8.0` on my Android tablet (dotrush also works with Neovim).

<img src="https://github.com/user-attachments/assets/7349153c-5851-44b2-9aa2-e83a6aa0b56f" />


This extension uses the `MSBuildLocator.RegisterDefaults()` for Roslyn. Maybe if you install dotnet via *apt*, it does some additional thinks for dotnet?

**Comment by JaneySprings** [comment]
I will add the following code in the next version:
```cs
var dotnetPath = Environment.GetEnvironmentVariable("DOTNET_ROOT");
if (!string.IsNullOrEmpty(dotnetPath))
    return MSBuildLocator.RegisterMSBuildPath(dotnetPath);      
```

I hope this helps to remove this error.

**Comment by DanielJonesEB** [comment]
I'm having the same error, although it seems like all functionality is working.

I'm using DotRush v24.12.340 on MacOS Sequoia 15.1.1, with .NET 9.0.101 installed via Homebrew. 

I'm so glad this extension exists. I have spent all day banging my head up against C# Dev Kit, which inexplicably failed to work with no error messages.
