### ISSUE TITLE
Debugging - coreclr not supported

### ISSUE THREAD

**Issue by DanielJonesEB** [JaneySprings/DotRush#8]
I'm sure this is user error, but I'm not sure how to debug a project.

I was previously using the C# and C# Dev Kit extensions, and the below `launch.json` worked to enable me to start my programmer with the debugger attached. Unfortunately C# Dev Kit refused to work in any other way, so I was thrilled to install DotRush and have it _just work_. 

Do I need to configure `launch.json` differently? I'm not really a C# developer and I'm trying to muddle my way through getting a 14-year-old project working, so please forgive my ignorance.

<img width="701" alt="image" src="https://github.com/user-attachments/assets/8ff1cede-c33f-41e4-b29b-cb858bc61550">

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": ".NET Core Launch (console)",
      "type": "coreclr",
      "request": "launch",
      "preLaunchTask": "build",
      "program": "${workspaceFolder}/ReproGame/bin/Debug/net8.0/ReproGame.dll",
      "args": [],
      "cwd": "${workspaceFolder}",
      "stopAtEntry": false,
      "console": "internalConsole"
    }
  ]
}

```

**Comment by JaneySprings** [comment]
Hi, @DanielJonesEB ! Do you use the latest version of the extension?
![image](https://github.com/user-attachments/assets/6561f96c-a85b-41d1-9e23-e7eee5c7f506)

**Comment by JaneySprings** [comment]
Maybe you have additional `C#` extensions enabled? Do you use `C#` or `C# DevKit` or something else?
For example, my list of the extensions:
![image](https://github.com/user-attachments/assets/2649f0a9-5f2c-4758-b85b-ed514adc2fa2)

**Comment by pushkin-** [comment]
this popped up for someone here. I reprod it a few times and then the issue went away. They say that when enabling the C# extension, they stopped getting this error. It doesn't repro for every workspace though. They should be running a net 8 project. I'll look into this on my end, but FYI.

it's possible in my case, restarting vscode helped; don't remember.
